/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export type paths = {
  "/dau": {
    /** Search */
    get: operations["search_dau_get"];
    /** Create Dau */
    post: operations["create_dau_dau_post"];
  };
  "/dau/import/{bridge}": {
    /** Import Dau */
    post: operations["import_dau_dau_import__bridge__post"];
  };
  "/dau/{id}": {
    /** Update Dau */
    put: operations["update_dau_dau__id__put"];
    /** Delete Dau */
    delete: operations["delete_dau_dau__id__delete"];
  };
  "/dau/bridge": {
    /** Get Bridge */
    get: operations["get_bridge_dau_bridge_get"];
  };
  "/dau/bridge/{bridge_name}": {
    /** Get Bridge */
    get: operations["get_bridge_dau_bridge__bridge_name__get"];
  };
  "/dau/ids": {
    /** Get Ids */
    get: operations["get_ids_dau_ids_get"];
  };
  "/health": {
    /** Health */
    get: operations["health_health_get"];
  };
};

export type webhooks = Record<string, never>;

export type components = {
  schemas: {
    /** Body_import_dau_dau_import__bridge__post */
    Body_import_dau_dau_import__bridge__post: {
      /** Files */
      files: string[];
    };
    /** DauSearchRequest */
    DauSearchRequest: {
      /** Name */
      name?: string | null;
      /** Bridge */
      bridge?: string | null;
      /** Collectionstationno */
      collectionStationNo?: string | null;
      /** Collectiondeviceno */
      collectionDeviceNo?: string | null;
      /** Ipaddress */
      ipAddress?: string | null;
      /** Samplerate */
      sampleRate?: string | null;
      /** Physicschannel */
      physicsChannel?: string | null;
      /** Installno */
      installNo?: string | null;
      /** Transferno */
      transferNo?: string | null;
      /** Monitorproject */
      monitorProject?: string | null;
      /** Devicetype */
      deviceType?: string | null;
      /** Manufacturer */
      manufacturer?: string | null;
      /** Specification */
      specification?: string | null;
      /** Deviceno */
      deviceNo?: string | null;
      /** Installlocation */
      installLocation?: string | null;
      /** Direction */
      direction?: string | null;
    };
    /** DauSearchResponse */
    DauSearchResponse: {
      /** Name */
      name?: string | null;
      /** Bridge */
      bridge?: string | null;
      /** Collectionstationno */
      collectionStationNo?: string | null;
      /** Collectiondeviceno */
      collectionDeviceNo?: string | null;
      /** Ipaddress */
      ipAddress?: string | null;
      /** Samplerate */
      sampleRate?: string | null;
      /** Physicschannel */
      physicsChannel?: string | null;
      /** Installno */
      installNo?: string | null;
      /** Transferno */
      transferNo?: string | null;
      /** Monitorproject */
      monitorProject?: string | null;
      /** Devicetype */
      deviceType?: string | null;
      /** Manufacturer */
      manufacturer?: string | null;
      /** Specification */
      specification?: string | null;
      /** Deviceno */
      deviceNo?: string | null;
      /** Installlocation */
      installLocation?: string | null;
      /** Direction */
      direction?: string | null;
      /** Id */
      id: number | null;
      /** Createddate */
      createdDate: string | null;
      /** Updateddate */
      updatedDate: string | null;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** HealthResponse */
    HealthResponse: {
      /** Status */
      status: string;
    };
    /** Page[DauSearchResponse] */
    Page_DauSearchResponse_: {
      /** Items */
      items: components["schemas"]["DauSearchResponse"][];
      /** Total */
      total: number | null;
      /** Page */
      page: number | null;
      /** Size */
      size: number | null;
      /** Pages */
      pages?: number | null;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
};

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = {

  /** Search */
  search_dau_get: {
    parameters: {
      query?: {
        /** @description Page number */
        page?: number;
        /** @description Page size */
        size?: number;
        name?: string | null;
        bridge?: string | null;
        collectionStationNo?: string | null;
        collectionDeviceNo?: string | null;
        ipAddress?: string | null;
        sampleRate?: string | null;
        physicsChannel?: string | null;
        installNo?: string | null;
        transferNo?: string | null;
        monitorProject?: string | null;
        deviceType?: string | null;
        manufacturer?: string | null;
        specification?: string | null;
        deviceNo?: string | null;
        installLocation?: string | null;
        direction?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Page_DauSearchResponse_"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Create Dau */
  create_dau_dau_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["DauSearchRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Import Dau */
  import_dau_dau_import__bridge__post: {
    parameters: {
      path: {
        bridge: string;
      };
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_import_dau_dau_import__bridge__post"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Update Dau */
  update_dau_dau__id__put: {
    parameters: {
      path: {
        id: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["DauSearchRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Delete Dau */
  delete_dau_dau__id__delete: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Bridge */
  get_bridge_dau_bridge_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": string[];
        };
      };
    };
  };
  /** Get Bridge */
  get_bridge_dau_bridge__bridge_name__get: {
    parameters: {
      path: {
        bridge_name: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["DauSearchResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Ids */
  get_ids_dau_ids_get: {
    parameters: {
      query?: {
        ids?: number[];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["DauSearchResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Health */
  health_health_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
    };
  };
};
