"""init database

Revision ID: 5a1201d3d92e
Revises: 
Create Date: 2024-06-05 14:30:46.601703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a1201d3d92e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dau_config',
    sa.Column('bridge', sa.String(length=128), nullable=False, comment='桥梁名称'),
    sa.Column('collection_station_no', sa.String(length=128), nullable=True, comment='采集站编号'),
    sa.Column('collection_device_no', sa.String(length=128), nullable=True, comment='采集设备编号'),
    sa.Column('ip_address', sa.String(length=128), nullable=True, comment='IP地址'),
    sa.Column('sample_rate', sa.String(length=128), nullable=True, comment='采样率'),
    sa.Column('physics_channel', sa.String(length=128), nullable=True, comment='物理通道'),
    sa.Column('install_no', sa.String(length=128), nullable=True, comment='安装点编号'),
    sa.Column('transfer_no', sa.String(length=128), nullable=True, comment='传输编号'),
    sa.Column('monitor_project', sa.String(length=128), nullable=True, comment='监测项目'),
    sa.Column('device_type', sa.String(length=128), nullable=True, comment='设备类型'),
    sa.Column('manufacturer', sa.String(length=128), nullable=True, comment='厂家名称'),
    sa.Column('specification', sa.String(length=128), nullable=True, comment='规格型号'),
    sa.Column('device_no', sa.String(length=128), nullable=True, comment='设备编号'),
    sa.Column('install_location', sa.String(length=128), nullable=True, comment='安装位置'),
    sa.Column('direction', sa.String(length=128), nullable=True, comment='方向'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=1024), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dau_config')
    # ### end Alembic commands ###
