image: node:22

# This folder is cached between builds
# https://docs.gitlab.com/ee/ci/yaml/index.html#cache
cache:
  paths:
    - node_modules/

build:
  stage: build
  script:
    - npm install
    - npm run build:electron
  environment: production
