"""add config

Revision ID: 1d47da11f27f
Revises: 
Create Date: 2024-06-12 10:40:54.584156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d47da11f27f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generator', schema=None) as batch_op:
        batch_op.add_column(sa.Column('config', sa.String(length=2048), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generator', schema=None) as batch_op:
        batch_op.drop_column('config')

    # ### end Alembic commands ###
