"""Add dau config

Revision ID: ead52927d409
Revises: 
Create Date: 2024-06-04 09:14:24.594668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ead52927d409'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dau_config',
    sa.Column('collection_station_no', sa.String(length=128), nullable=True),
    sa.Column('collection_device_no', sa.String(length=128), nullable=True),
    sa.Column('ip_address', sa.String(length=128), nullable=True),
    sa.Column('sample_rate', sa.String(length=128), nullable=True),
    sa.Column('physics_channel', sa.String(length=128), nullable=True),
    sa.Column('install_no', sa.String(length=128), nullable=True),
    sa.Column('transfer_no', sa.String(length=128), nullable=True),
    sa.Column('monitor_project', sa.String(length=128), nullable=True),
    sa.Column('device_type', sa.String(length=128), nullable=True),
    sa.Column('manufacturer', sa.String(length=128), nullable=True),
    sa.Column('specification', sa.String(length=128), nullable=True),
    sa.Column('device_no', sa.String(length=128), nullable=True),
    sa.Column('install_location', sa.String(length=128), nullable=True),
    sa.Column('direction', sa.String(length=128), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=1024), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('generator', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dau_config_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('generator_dau_config', 'dau_config', ['dau_config_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generator', schema=None) as batch_op:
        batch_op.drop_constraint('generator_dau_config', type_='foreignkey')
        batch_op.drop_column('dau_config_id')

    op.drop_table('dau_config')
    # ### end Alembic commands ###
